### ISSUE TITLE
Oauth2 help request.

### ISSUE THREAD

**Issue by ItsMax123** [lucascphillips/aut-bot-app#90]
Hello, 
I am looking for someone who can help me build a discord-bot dashboard to my website.
Any help would be very appreciated since at this point I've looking at pretty much every tutorial on this subject and nothing has worked for me.
(The bot is in over 950 discord servers.)

I might not get GitHub notifications so please DM me on discord: **ItsMax123#6798** if you are able to help.

Thanks!

**Comment by johnyburd** [comment]
Hey Max, check out our discord server and a few people should be able to help you out [discord.gg/svrRrSe](https://discord.gg/svrRrSe)
